### PR TITLE
Produce overlaid graphs for binary sizes also

### PR DESCRIPTION
**Pull request by punchagan**

### CODE REVIEW

**Comment by art-w** [comment]
Thanks, LGTM!

I remember seeing a patch to current-bench frontend for `NaN` values, was it for this PR as seen in https://autumn.ocamllabs.io/art-w/ocaml/pull/9?worker=grumpy&image=bench.Dockerfile ?

**Comment by punchagan** [comment]
> I remember seeing a patch to current-bench frontend for `NaN` values, was it for this PR as seen in https://autumn.ocamllabs.io/art-w/ocaml/pull/9?worker=grumpy&image=bench.Dockerfile ?

Not sure what the bug is here. I'm taking a look!

**Comment by punchagan** [comment]
Essentially, what's happening here is I changed the regex used to filter out the files to include in the binary size count a couple of times. The current version ignores the binary files generated in hidden directories. This causes `NaN` values to be displayed for the sizes for the files which have been ignored, for instance, `decompress/cmx`, `decompress/cmt`, ... etc. 

Pull request https://github.com/ocurrent/current-bench/pull/323/ on Current bench would change the display to show a `?` instead of a `NaN` in the legend.

Below is a list of files ignored for the `decompress` binaries metric, and further below is a list of included files.

Excluded files because they are in hidden directories (starting with a `.`)
```
36	./_build/default/lib/.lz.objs/native/lz.o
8	./_build/default/lib/.lz.objs/native/lz.cmx
12	./_build/default/lib/.lz.objs/byte/lz.cmti
76	./_build/default/lib/.lz.objs/byte/lz.cmo
4	./_build/default/lib/.lz.objs/byte/lz.cmi
236	./_build/default/lib/.lz.objs/byte/lz.cmt
0	./_build/default/lib/.merlin-exist-lib-decompress.zl
0	./_build/default/lib/.merlin-exist-lib-decompress.gz
8	./_build/default/lib/.lzo.objs/native/lzo.cmx
64	./_build/default/lib/.lzo.objs/native/lzo.o
12	./_build/default/lib/.lzo.objs/byte/lzo.cmti
300	./_build/default/lib/.lzo.objs/byte/lzo.cmt
4	./_build/default/lib/.lzo.objs/byte/lzo.cmi
120	./_build/default/lib/.lzo.objs/byte/lzo.cmo
0	./_build/default/lib/.merlin-exist-lib-decompress.de
108	./_build/default/lib/.gz.objs/native/gz.o
12	./_build/default/lib/.gz.objs/native/gz.cmx
8	./_build/default/lib/.gz.objs/byte/gz.cmi
60	./_build/default/lib/.gz.objs/byte/gz.cmti
180	./_build/default/lib/.gz.objs/byte/gz.cmo
380	./_build/default/lib/.gz.objs/byte/gz.cmt
0	./_build/default/lib/.merlin-exist-lib-decompress.lzo
8	./_build/default/lib/.zl.objs/native/zl.cmx
68	./_build/default/lib/.zl.objs/native/zl.o
56	./_build/default/lib/.zl.objs/byte/zl.cmti
8	./_build/default/lib/.zl.objs/byte/zl.cmi
272	./_build/default/lib/.zl.objs/byte/zl.cmt
124	./_build/default/lib/.zl.objs/byte/zl.cmo
0	./_build/default/lib/.merlin-exist-lib-rfc1951
4	./_build/default/lib/.merlin-conf/lib-decompress.lz
4	./_build/default/lib/.merlin-conf/lib-rfc1951
4	./_build/default/lib/.merlin-conf/lib-decompress.gz
4	./_build/default/lib/.merlin-conf/lib-decompress.zl
4	./_build/default/lib/.merlin-conf/lib-decompress.de
4	./_build/default/lib/.merlin-conf/lib-decompress.lzo
0	./_build/default/lib/.merlin-exist-lib-decompress.lz
32	./_build/default/lib/.rfc1951.objs/native/rfc1951.cmx
372	./_build/default/lib/.rfc1951.objs/native/rfc1951.o
72	./_build/default/lib/.rfc1951.objs/byte/rfc1951.cmi
1988	./_build/default/lib/.rfc1951.objs/byte/rfc1951.cmt
768	./_build/default/lib/.rfc1951.objs/byte/rfc1951.cmo
296	./_build/default/lib/.de.objs/native/de.o
28	./_build/default/lib/.de.objs/native/de.cmx
100	./_build/default/lib/.de.objs/byte/de.cmti
16	./_build/default/lib/.de.objs/byte/de.cmi
748	./_build/default/lib/.de.objs/byte/de.cmo
1928	./_build/default/lib/.de.objs/byte/de.cmt
0	./_build/default/bindings/generator/.merlin-exist-exe-generate
4	./_build/default/bindings/generator/.merlin-conf/exe-generate
12	./_build/default/bindings/generator/.generate.eobjs/native/dune__exe__Generate.o
4	./_build/default/bindings/generator/.generate.eobjs/native/dune__exe__Generate.cmx
4	./_build/default/bindings/generator/.generate.eobjs/byte/dune__exe__Generate.cmi
8	./_build/default/bindings/generator/.generate.eobjs/byte/dune__exe__Generate.cmo
20	./_build/default/bindings/generator/.generate.eobjs/byte/dune__exe__Generate.cmt
0	./_build/default/bindings/stubs/.merlin-exist-lib-gen_decompress_bindings
4	./_build/default/bindings/stubs/.decompress.eobjs/native/dune__exe__Apply_bindings.cmx
4	./_build/default/bindings/stubs/.decompress.eobjs/native/dune__exe.cmx
4	./_build/default/bindings/stubs/.decompress.eobjs/native/dune__exe__Decompress_bindings.cmx
8	./_build/default/bindings/stubs/.decompress.eobjs/native/dune__exe__Decompress_bindings.o
4	./_build/default/bindings/stubs/.decompress.eobjs/native/dune__exe__Decompress.cmx
4	./_build/default/bindings/stubs/.decompress.eobjs/native/dune__exe__Apply_bindings.o
4	./_build/default/bindings/stubs/.decompress.eobjs/native/dune__exe.o
4	./_build/default/bindings/stubs/.decompress.eobjs/native/dune__exe__Decompress.o
4	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe__Decompress_bindings.cmi
4	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe__Apply_bindings.cmo
4	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe.cmi
4	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe__Apply_bindings.cmi
4	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe__Decompress.cmo
4	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe.cmo
12	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe__Apply_bindings.cmt
4	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe__Decompress.cmi
20	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe__Decompress_bindings.cmo
36	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe__Decompress_bindings.cmt
4	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe__Decompress.cmt
4	./_build/default/bindings/stubs/.decompress.eobjs/byte/dune__exe.cmt
20	./_build/default/bindings/stubs/.gen_decompress_bindings.objs/native/gen_decompress_bindings.o
4	./_build/default/bindings/stubs/.gen_decompress_bindings.objs/native/gen_decompress_bindings.cmx
28	./_build/default/bindings/stubs/.gen_decompress_bindings.objs/byte/gen_decompress_bindings.cmo
52	./_build/default/bindings/stubs/.gen_decompress_bindings.objs/byte/gen_decompress_bindings.cmt
4	./_build/default/bindings/stubs/.gen_decompress_bindings.objs/byte/gen_decompress_bindings.cmi
4	./_build/default/bindings/stubs/.merlin-conf/exe-decompress
4	./_build/default/bindings/stubs/.merlin-conf/lib-gen_decompress_bindings
0	./_build/default/bindings/stubs/.merlin-exist-exe-decompress
32	./_build/default/test/.test_deflate.eobjs/native/dune__exe__Test_deflate.o
4	./_build/default/test/.test_deflate.eobjs/native/dune__exe__Test_deflate.cmx
32	./_build/default/test/.test_deflate.eobjs/byte/dune__exe__Test_deflate.cmo
60	./_build/default/test/.test_deflate.eobjs/byte/dune__exe__Test_deflate.cmt
4	./_build/default/test/.test_deflate.eobjs/byte/dune__exe__Test_deflate.cmi
0	./_build/default/test/.merlin-exist-exe-test_deflate
0	./_build/default/test/.merlin-exist-exe-test
4	./_build/default/test/.merlin-conf/exe-test
4	./_build/default/test/.merlin-conf/exe-test_deflate
4	./_build/default/bin/.pipe.eobjs/native/dune__exe__Pipe.cmx
36	./_build/default/bin/.pipe.eobjs/native/dune__exe__Pipe.o
92	./_build/default/bin/.pipe.eobjs/byte/dune__exe__Pipe.cmt
4	./_build/default/bin/.pipe.eobjs/byte/dune__exe__Pipe.cmi
48	./_build/default/bin/.pipe.eobjs/byte/dune__exe__Pipe.cmo
0	./_build/default/bin/.merlin-exist-exe-pipe
4	./_build/default/bin/.merlin-conf/exe-pipe
0	./_build/default/fuzz/.merlin-exist-exe-fuzz
0	./_build/default/fuzz/.merlin-exist-exe-fuzz_ns
4	./_build/default/fuzz/.merlin-conf/exe-fuzz
4	./_build/default/fuzz/.merlin-conf/exe-fuzz_ns
0	./_build/default/.dune/.dune-keep
4	./_build/.aliases/default/all-00000000000000000000000000000000
4	./_build/.aliases/default/lib/default-00000000000000000000000000000000
0	./_build/.aliases/default/lib/default-43c882e73206c34190dec664a5078cf0
4	./_build/.aliases/default/bindings/all-00000000000000000000000000000000
4	./_build/.aliases/default/bindings/default-00000000000000000000000000000000
4	./_build/.aliases/default/bindings/generator/default-00000000000000000000000000000000
4	./_build/.aliases/default/bindings/stubs/all-00000000000000000000000000000000
4	./_build/.aliases/default/bindings/stubs/default-00000000000000000000000000000000
4	./_build/.aliases/default/test/corpus/all-00000000000000000000000000000000
4	./_build/.aliases/default/test/corpus/default-00000000000000000000000000000000
4	./_build/.aliases/default/test/bin/default-00000000000000000000000000000000
4	./_build/.aliases/default/bin/all-00000000000000000000000000000000
4	./_build/.aliases/default/bin/default-00000000000000000000000000000000
24	./_build/.db
64	./_build/.digest-db
```

Included files
```
472	./test/corpus/pic
752	./test/corpus/book1
244	./test/corpus/obj2
92	./test/corpus/trans
100	./test/corpus/geo
24	./test/corpus/obj1
120	./_build/default/lib/gz.cmxs
68	./_build/default/lib/lzo.a
40	./_build/default/lib/lz.a
308	./_build/default/lib/de.a
384	./_build/default/lib/rfc1951.a
80	./_build/default/lib/lzo.cmxs
4	./_build/default/lib/rfc1951.cmxa
4	./_build/default/lib/de.cmxa
4	./_build/default/lib/zl.cmxa
76	./_build/default/lib/lz.cma
768	./_build/default/lib/rfc1951.cma
88	./_build/default/lib/zl.cmxs
108	./_build/default/lib/gz.a
360	./_build/default/lib/rfc1951.cmxs
748	./_build/default/lib/de.cma
292	./_build/default/lib/de.cmxs
4	./_build/default/lib/lzo.cmxa
4	./_build/default/lib/lz.cmxa
72	./_build/default/lib/zl.a
52	./_build/default/lib/lz.cmxs
124	./_build/default/lib/zl.cma
180	./_build/default/lib/gz.cma
120	./_build/default/lib/lzo.cma
4	./_build/default/lib/gz.cmxa
2936	./_build/default/bindings/generator/generate.exe
20	./_build/default/bindings/stubs/gen_decompress_bindings.a
28	./_build/default/bindings/stubs/gen_decompress_bindings.cma
4028	./_build/default/bindings/stubs/libdecompress.a
32	./_build/default/bindings/stubs/gen_decompress_bindings.cmxs
3872	./_build/default/bindings/stubs/decompress.exe.o
24	./_build/default/bindings/stubs/gen_decompress.o
4	./_build/default/bindings/stubs/gen_decompress_bindings.cmxa
8	./_build/default/bindings/stubs/init.o
504	./_build/default/test/corpus/pic
752	./_build/default/test/corpus/book1
244	./_build/default/test/corpus/obj2
92	./_build/default/test/corpus/trans
100	./_build/default/test/corpus/geo
24	./_build/default/test/corpus/obj1
3632	./_build/default/test/test_deflate.exe
2568	./_build/default/bin/pipe.exe
```

**Comment by art-w** [comment]
Oh I see, nice investigation! An issue with dune libraries is that the following extensions end up in a hidden `.something.eobjs` directory:

```
cmi:NaNmb
cmo:NaNmb
cmt:NaNmb
cmti:NaNmb
cmx:NaNmb
```

(and that's the files the ocaml maintainers wanted to keep an eye on)

**Comment by punchagan** [comment]
I've changed the filtering regex to include the files in `.something.eobjs`directories.

**Comment by art-w** [comment]
Thanks!

**Pull request merged**
